### ISSUE TITLE
Weird error.

### ISSUE THREAD

**Issue by g0dzcsgo** [thunder-red-star/discord.js-userbot#2]

**Comment by thunder-red-star** [comment]
Not sure as this package is literally v12.5.3 but 1 line was changed. I don't know too much about the code itself, so your best bet is to ask the owners of the original Discord.js. 

Or it could possibly be that selfbots don't support webhooks?

**Comment by g0dzcsgo** [comment]
> Not sure as this package is literally v12.5.3 but 1 line was changed. I don't know too much about the code itself, so your best bet is to ask the owners of the original Discord.js.
> 
> Or it could possibly be that selfbots don't support webhooks?

I literally tried a new VPS, freshly installed node 12. And downloaded your version of discord.js and i get the same error.

**Comment by g0dzcsgo** [comment]
And i like this version cause you can actually do

channel.send(message.embeds)

And it sends the embeds from a copied message, but you cant do that in newer versions :/ So my best bet is to get this to work!

**Comment by thunder-red-star** [comment]
What webhook package did you get? I'll look at it to see if it causes errors...

**Comment by g0dzcsgo** [comment]
> What webhook package did you get? I'll look at it to see if it causes errors...

I just told you, i even tried on a new vps with ONLY your package and freshly installed Node & NPM and still that same error. And i got no idea what causes it.

**Comment by thunder-red-star** [comment]
I'm looking at it. I'll respond if I find out what's going on. Package works fine on my end with node v12.x.x and npm v6.x.x so I'm not sure

**Comment by g0dzcsgo** [comment]
Well I can give you a login to my test VPS, and you can give it a go?

**Comment by thunder-red-star** [comment]
Sure, you can send them here (or to Discord, ThunderRedStar#3827)

**Comment by g0dzcsgo** [comment]
> Sure, you can send them here (or to Discord, ThunderRedStar#3827)

Added you on discord! I am cool#1337

**Comment by thunder-red-star** [comment]
Accepted!

**Comment by thunder-red-star** [comment]
Seems logging in works with `djs-self`, you might have required `discord`, which I fixed in your index.js
